'use strict';

/***********************************************************************************************************************************************
 * MIGRATION TEMPLATE
 ***********************************************************************************************************************************************
 * @description
 */


module.exports = (name='') => {
  return `
'use strict';

/***********************************************************************************************************************************************
 * NODE DB MIGRATE - ${name.toUpperCase()}
 ***********************************************************************************************************************************************
 * @author File generated by @liveaxle/node-pg-migrate
 * @description
 * 
 */

/**
 * [exports description]
 * @type {Object}
 */
module.exports = {
  up, down
};

/**
 * [up description]
 * @return {[type]} [description]
 */
async function up(client) {

}

/**
 * [down description]
 * @return {[type]} [description]
 */
async function down(client) {

}
  `;
};
